version: '3.8'
services:
  app:
    build: .
    restart: always
    volumes:
      - ./credential.json:/credential.json:ro
      - ${XDG_RUNTIME_DIR}/pulse/native/:${XDG_RUNTIME_DIR}/pulse/native
      - ${HOME}/.config/pulse/:/root/.config/pulse
      - ./sounds:/root/sounds
      - ./voices:/root/voices
    environment:
      PYTHONUNBUFFERED: 1
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      FIREBASE_SECRET_PATH: /credential.json
      # FIREBASE_DATABASE_URL: https://YOUR_PROJECT_ID.firebaseio.com/
    env_file:
      - ./.env

